project: ivtlr
save_path: "/home/csalt/Haider/DVLM/IVT-LR/qwen_vl/output"
name: qwen_IVTLR_m3cot_no_vis
model_name: Qwen/Qwen2-VL-2B-Instruct

epochs_per_stage: 4
max_latent_stage: 5
pad_latent_to_max: True

load_model_path: None
seed: 0
resume: 0
bf16: True
batch_size_training: 2
debug: False
gradient_accumulation_steps: 8
num_epochs: 16
lr: !!float "4e-5"