project: ivtlr
save_path: "outuputs_dynamic_ivtlr"
name: qwen_IVTLR_m3cot
model_name: Qwen/Qwen2-VL-2B-Instruct

epochs_per_stage: 4
max_latent_stage: 15
pad_latent_to_max: True
hidden_state_alignment: True
disable_visual_insert: True
rho_schedule: [0.0, 0.1, 0.2, 0.3, 0.4, 0.4, 0.5, 0.5, 0.6, 0.6, 0.7, 0.7, 0.8, 0.8, 0.9, 1.0, 1.0, 1.0, 1.0, 1.0]
lambda_hidden_schedule: [0.0, 0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.05, 0.06, 0.06, 0.05, 0.05, 0.04, 0.3, 0.02, 0.01, 0.0, 0.0, 0.0, 0.0]

load_model_path: None
seed: 0
resume: 0
bf16: True
batch_size_training: 2
debug: False
gradient_accumulation_steps: 8
num_epochs: 20
lr: !!float "4e-5"
