project: ivtlr
save_path: outputs_dynamic_ivtlr
name: qwen_IVTLR_m3cot_no_hidden_distill_8_steps_fixed_mask
model_name: Qwen/Qwen2-VL-2B-Instruct
epochs_per_stage: 4
max_latent_stage: 8
pad_latent_to_max: true
hidden_state_alignment: false
disable_visual_insert: true
prefix_span: false
fixed_mask_step_curriculum: true
fixed_mask_max_steps: 8
fixed_mask_schedule:
- 0
- 0
- 1
- 1
- 2
- 2
- 3
- 3
- 4
- 4
- 5
- 5
- 6
- 6
- 7
- 7
- 8
- 8
- 8
- 8
rho_schedule:
- 0.0
- 0.0
- 0.1
- 0.1
- 0.2
- 0.2
- 0.3
- 0.3
- 0.4
- 0.5
- 0.6
- 0.6
- 0.7
- 0.7
- 0.8
- 0.8
- 1.0
- 1.0
- 1.0
- 1.0
lambda_hidden_schedule:
- 0.0
- 0.005
- 0.01
- 0.02
- 0.03
- 0.04
- 0.05
- 0.05
- 0.06
- 0.06
- 0.05
- 0.05
- 0.04
- 0.03
- 0.02
- 0.01
- 0.0
- 0.0
- 0.0
- 0.0
load_model_path: "/home/csalt/Haider/DVLM/IVT-LR/qwen_vl/outputs_dynamic_ivtlr/qwen_IVTLR_m3cot_no_hidden_distill_8_steps_fixed_mask/epoch_10_full_model_fp32.pth"
seed: 0
resume: 10
bf16: true
batch_size_training: 2
debug: false
gradient_accumulation_steps: 8
num_epochs: 20
lr: 4.0e-05
